pipeline {
    agent any
    tools {
        maven 'maven 3.8.2'
        jdk 'JDK 1.8'
    }
    stages {
        stage("git clone") {
            steps {
                git branch: 'dev', url: 'https://github.com/jyorien/DevopS'
            }
        }
        stage("build") {
            steps {
                bat 'mvn -f Devops/pom.xml clean install'
        
            }
        }
        stage("test") {
            steps {
                bat 'mvn -f Devops/pom.xml test'    
            }
        }
        stage("build docker image") {
            steps {
                dir("${env.WORKSPACE}/DevopS") {
                bat 'dir'
                bat 'docker build -t jyorin/user-manage-jenkins -f Dockerfile .'
                }

            }
        }
        stage("push to docker hub") {
            steps {
             
                withCredentials([string(credentialsId: 'dockerpwd', variable: 'passdocker')]) {
                    bat "docker login -u jyorin -p ${passdocker}"
                }
                bat "docker push jyorin/user-manage-jenkins"
            }
        }
        
        
    }
}
