pipeline {
    agent any
    tools {
        maven 'maven 3.8.2'
        jdk 'JDK 1.8'
    }
    stages {
        stage("git clone") {
            steps {
                git branch: 'dev', url: 'https://github.com/jyorien/DevopS'
            }
        }
        stage("build") {
            steps {
                bat 'mvn -f Devops/pom.xml clean install'
            
            }
        }
        stage("test") {
            steps {
                bat 'mvn test'    
            }
        }
    }
}
